# Generated by Django 4.2.3 on 2023-07-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=20)),
                ('banco', models.CharField(choices=[('Nu', 'Nubank'), ('CE', 'Caixa Economica')], max_length=2)),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa fisica'), ('PJ', 'Pessoa jurídica')], max_length=2)),
                ('valor', models.FloatField()),
                ('icone', models.FileField(upload_to='icones')),
            ],
        ),
    ]
